// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmOjS1aTqRDpdsrfUO_uznULlwBFB97c',
    appId: '1:218612040228:web:bd7b2dfaab45d0e7e20eb1',
    messagingSenderId: '218612040228',
    projectId: 'hancod-3576e',
    authDomain: 'hancod-3576e.firebaseapp.com',
    storageBucket: 'hancod-3576e.firebasestorage.app',
    measurementId: 'G-5XQKT3ZGFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcs9-2NeIis7R0JE1TEmM0QLC20VTabHI',
    appId: '1:218612040228:android:b6d313587697a426e20eb1',
    messagingSenderId: '218612040228',
    projectId: 'hancod-3576e',
    storageBucket: 'hancod-3576e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCn2ejJq7d10sGsdSZH0MIGcV4hTw-Cf4',
    appId: '1:218612040228:ios:644fd9c58b31bab7e20eb1',
    messagingSenderId: '218612040228',
    projectId: 'hancod-3576e',
    storageBucket: 'hancod-3576e.firebasestorage.app',
    iosBundleId: 'com.example.hancod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCn2ejJq7d10sGsdSZH0MIGcV4hTw-Cf4',
    appId: '1:218612040228:ios:644fd9c58b31bab7e20eb1',
    messagingSenderId: '218612040228',
    projectId: 'hancod-3576e',
    storageBucket: 'hancod-3576e.firebasestorage.app',
    iosBundleId: 'com.example.hancod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZmOjS1aTqRDpdsrfUO_uznULlwBFB97c',
    appId: '1:218612040228:web:d3ed87745ae9d2bde20eb1',
    messagingSenderId: '218612040228',
    projectId: 'hancod-3576e',
    authDomain: 'hancod-3576e.firebaseapp.com',
    storageBucket: 'hancod-3576e.firebasestorage.app',
    measurementId: 'G-XV645ZXSBM',
  );
}
